version: 2

jobs:
  build:
    docker:
      - image: buildpack-deps:18.04-scm
    steps:
      - run:
          name: Preparing Base image with dependencies
          command: |
            set -x
            DOCKER_VERSION="18.03.1-ce"
            apt-get update
            apt-get install -y make makeself
            curl -sSL https://download.docker.com/linux/static/stable/x86_64/docker-${DOCKER_VERSION}.tgz | tar --extract --gzip --directory="/usr/bin" --strip-components=1
      - setup_remote_docker:
          version: 18.03.1-ce
          docker_layer_caching: true
      - checkout
      - run: 
          name: Build installer.run file
          command : |
            make package
      - persist_to_workspace:
          root: ./
          paths:
          - installer.run
  publish-github-release:
    docker:
      - image: cibuilds/github:0.10
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            set -o xtrace;
            VERSION="$(git describe --always --exact-match --abbrev=0 HEAD)"
            ghr \
              -t ${GITHUB_TOKEN} \
              -u ${CIRCLE_PROJECT_USERNAME} \
              -r ${CIRCLE_PROJECT_REPONAME} \
              -c ${CIRCLE_SHA1} \
              -delete \
              ${VERSION} \
              /tmp/artifacts/

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - publish-github-release:
          requires:
            - build
          context: GitHub
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
